### ISSUE TITLE
Anomaly When Testing `pay_prefunded_invoice` extrinsic in prefunding pallet

### ISSUE THREAD

**Issue by dharjeezy** [totem-tech/totem-parachains#30]
When you want to `pay_prefunded_invoice` You need to first `prefund_someone`
Prefunding someone sets the status to `Locked` for the owner and `Unlocked` for the beneficiary.

But then, `pay_prefunded_invoice` is expecting the status to be `Locked` for the owner and `Locked` for the beneficiary.

In what case will the status be `Locked` for the owner and `Locked` for the beneficiary? I can't seem to find that case where status is being set to that for the `PrefundingHashOwner` storage

**Comment by chrisdcosta** [comment]
The beneficiary must accept the order for it to be locked for them. When both locks are in place then the order is deemed to have been accepted by the person doing the work. 

If the beneficiary has not accepted the order by a certain time the owner can pull the money back, but if it is already accepted, then the owner cannot pull the money back, and any issues are disputes that need to be resolved by both parties, otherwise nobody gets the money and it stays locked.
